### ISSUE TITLE
apple supplied sed breaks parameter parsing in very particular circumstances

### ISSUE THREAD

**Issue by cosgroma** [chilladx/config-parser#4]
Just tracked down a very annoying bug. It is not a bug with config-parser but just thought I would throw it out there. If a parameter ends in 't' then the sed supplied by apple will remove the t. So 'test' becomes 'tes'. I installed posix sed and that fixed my problem. Just thought you might want to know. Thanks for this, I've been loving it.

**Comment by chilladx** [comment]
@cosgroma I've never been able to reproduce your bug. Could you please add transcript/example?

**Comment by sukima** [comment]
I've run into this trouble before in Apple sed. seems it can not handle the `\t` even when you use the `-e` argument. When I do sed commands that use tabs I default to using literal tabs:

    sed 's/[ ⇥]*=[ ⇥]*/=/g'

Where the `⇥` is a actual tab character (<kbd>Ctrl-V</kbd><kbd>Ctrl-I</kbd> in Vim).

GNU sed doesn't do this. Personally I think the Unix gurus at Apple only _pretend_ they know what they are doing.

**Comment by sukima** [comment]
Here is a link to others with the same problem: http://stackoverflow.com/questions/5398395/how-can-i-insert-a-tab-character-with-sed-on-os-x

**Comment by chilladx** [comment]
My concern is that it's too specific for OS X, and will make the code incompatible with GNU sed. At the very least, the code needs to make the difference between both platform, and apply the correct syntax.
As it's ugly code, I propose we add it to the doc, and leave the project clean.

**Comment by sukima** [comment]
FYI for those looking for a Mac OS X compatible version I have a complete rewrite fork at https://github.com/sukima/config-parser (with tests!)

**Comment by chilladx** [comment]
Thanks, @sukima! I updated the README to mention your fork, thus I'll close this issue.

**Comment by RichardBronosky** [comment]
> Here is a link to others with the same problem: http://stackoverflow.com/questions/5398395/how-can-i-insert-a-tab-character-with-sed-on-os-x

If you need to deal with literal tabs and you know you are writing for a reasonably bash-like shell, you should use the "other" answer to that question. https://stackoverflow.com/a/38023442

In https://github.com/sukima/config-parser/commit/d0af5cdb2ec652954f6b9bae2033f3712a07ec2c#r46904423
